-- No destructive rollback of any persisted lifecycle foundation data.
CREATE TEMP TABLE lifecycle_backout_guard (safe INTEGER NOT NULL CHECK(safe=1));
INSERT INTO lifecycle_backout_guard SELECT CASE WHEN EXISTS(SELECT 1 FROM lifecycle_contracts) THEN 0 ELSE 1 END;
INSERT INTO lifecycle_backout_guard SELECT CASE WHEN EXISTS(SELECT 1 FROM lifecycle_revisions) THEN 0 ELSE 1 END;
INSERT INTO lifecycle_backout_guard SELECT CASE WHEN EXISTS(SELECT 1 FROM lifecycle_revision_positions) THEN 0 ELSE 1 END;
INSERT INTO lifecycle_backout_guard SELECT CASE WHEN EXISTS(SELECT 1 FROM lifecycle_rule_snapshots) THEN 0 ELSE 1 END;
INSERT INTO lifecycle_backout_guard SELECT CASE WHEN EXISTS(SELECT 1 FROM lifecycle_consents) THEN 0 ELSE 1 END;
INSERT INTO lifecycle_backout_guard SELECT CASE WHEN EXISTS(SELECT 1 FROM lifecycle_need_targets) THEN 0 ELSE 1 END;
INSERT INTO lifecycle_backout_guard SELECT CASE WHEN EXISTS(SELECT 1 FROM lifecycle_need_claims) THEN 0 ELSE 1 END;
INSERT INTO lifecycle_backout_guard SELECT CASE WHEN EXISTS(SELECT 1 FROM lifecycle_directions) THEN 0 ELSE 1 END;
INSERT INTO lifecycle_backout_guard SELECT CASE WHEN EXISTS(SELECT 1 FROM lifecycle_commands) THEN 0 ELSE 1 END;
INSERT INTO lifecycle_backout_guard SELECT CASE WHEN EXISTS(SELECT 1 FROM lifecycle_movements) THEN 0 ELSE 1 END;
INSERT INTO lifecycle_backout_guard SELECT CASE WHEN EXISTS(SELECT 1 FROM lifecycle_supply_bindings) THEN 0 ELSE 1 END;
DROP TABLE lifecycle_backout_guard;
DROP TRIGGER lifecycle_supply_head_no_replace;
DROP TRIGGER lifecycle_claim_id_no_replace;
DROP TRIGGER lifecycle_position_key_no_replace;
DROP TRIGGER lifecycle_revision_kind_no_replace;
DROP TRIGGER lifecycle_materialized_position_update;
DROP TRIGGER lifecycle_materialized_position_insert;
DROP TRIGGER lifecycle_shared_rebind_guard;
DROP TRIGGER lifecycle_movement_event_no_replace;
DROP TRIGGER lifecycle_supply_bindings_no_replace;
DROP TRIGGER lifecycle_movements_no_replace;
DROP TRIGGER lifecycle_commands_no_replace;
DROP TRIGGER lifecycle_directions_no_replace;
DROP TRIGGER lifecycle_need_claims_no_replace;
DROP TRIGGER lifecycle_consents_no_replace;
DROP TRIGGER lifecycle_rule_snapshots_no_replace;
DROP TRIGGER lifecycle_revision_positions_no_replace;
DROP TRIGGER lifecycle_revisions_no_replace;
DROP TRIGGER lifecycle_contracts_no_replace;
DROP TRIGGER lifecycle_shared_hold_identity;
DROP TRIGGER lifecycle_shared_hold_guard;
DROP TRIGGER lifecycle_movement_owner;
DROP TRIGGER lifecycle_snapshot_sealed;
DROP TRIGGER lifecycle_accepted_monotone;
DROP TRIGGER lifecycle_root_initial;
DROP TRIGGER lifecycle_supply_delete;
DROP TRIGGER lifecycle_supply_update;
DROP TRIGGER lifecycle_supply_owner;
DROP TRIGGER lifecycle_movement_delete;
DROP TRIGGER lifecycle_movement_update;
DROP TRIGGER lifecycle_command_delete;
DROP TRIGGER lifecycle_command_update;
DROP TRIGGER lifecycle_command_guard;
DROP TRIGGER lifecycle_direction_identity;
DROP TRIGGER lifecycle_direction_guard;
DROP TRIGGER lifecycle_claim_delete;
DROP TRIGGER lifecycle_claim_update;
DROP TRIGGER lifecycle_claim_insert;
DROP TRIGGER lifecycle_snapshot_delete;
DROP TRIGGER lifecycle_snapshot_update;
DROP TRIGGER lifecycle_consent_delete;
DROP TRIGGER lifecycle_consent_update;
DROP TRIGGER lifecycle_consent_guard;
DROP TRIGGER lifecycle_accepted_guard;
DROP TRIGGER lifecycle_current_guard;
DROP TRIGGER lifecycle_seal_guard;
DROP TRIGGER lifecycle_position_delete;
DROP TRIGGER lifecycle_position_update;
DROP TRIGGER lifecycle_position_insert;
DROP TRIGGER lifecycle_revision_delete;
DROP TRIGGER lifecycle_revision_immutable;
DROP TRIGGER lifecycle_revision_author;
DROP TRIGGER lifecycle_trade_identity;
DROP TRIGGER lifecycle_contract_delete;
DROP TRIGGER lifecycle_contract_identity;
DROP TRIGGER lifecycle_contract_insert_guard;
DROP TABLE lifecycle_supply_bindings;
DROP TABLE lifecycle_movements;
DROP TABLE lifecycle_commands;
DROP TABLE lifecycle_directions;
DROP TABLE lifecycle_need_claims;
DROP TABLE lifecycle_need_targets;
DROP TABLE lifecycle_consents;
DROP TABLE lifecycle_rule_snapshots;
DROP TABLE lifecycle_revision_positions;
DROP TABLE lifecycle_revisions;
DROP TABLE lifecycle_contracts;
