CREATE TEMP TABLE lifecycle_address_down_guard(n INTEGER CHECK(n=0));
INSERT INTO lifecycle_address_down_guard SELECT COUNT(*) FROM lifecycle_address_book;
INSERT INTO lifecycle_address_down_guard SELECT COUNT(*) FROM lifecycle_address_snapshots;
INSERT INTO lifecycle_address_down_guard SELECT COUNT(*) FROM lifecycle_address_book_commands;
DROP TABLE lifecycle_address_down_guard;
DROP TRIGGER lifecycle_address_release_no_replace;
DROP TRIGGER lifecycle_address_snapshot_no_replace;
DROP TRIGGER lifecycle_address_release_immutable;
DROP TRIGGER lifecycle_address_release_owner;
DROP TRIGGER lifecycle_address_choice_update;
DROP TRIGGER lifecycle_address_choice_insert;
DROP TRIGGER lifecycle_address_snapshot_immutable;
DROP TRIGGER lifecycle_address_snapshot_owner;
DROP TRIGGER lifecycle_address_book_owner;
DROP TABLE lifecycle_address_releases;
DROP TABLE lifecycle_address_choices;
DROP TABLE lifecycle_address_snapshots;
DROP TABLE lifecycle_address_book_commands;
DROP TABLE lifecycle_address_book;
