CREATE TEMP TABLE lifecycle_receipts_down_guard(n INTEGER CHECK(n=0));
INSERT INTO lifecycle_receipts_down_guard SELECT COUNT(*) FROM lifecycle_receipts;
INSERT INTO lifecycle_receipts_down_guard SELECT COUNT(*) FROM lifecycle_delivery_problems;
DROP TABLE lifecycle_receipts_down_guard;
DROP TRIGGER lifecycle_receipt_event_replace;
DROP TRIGGER lifecycle_receipt_event_delete;
DROP TRIGGER lifecycle_receipt_event_update;
DROP TRIGGER lifecycle_receipt_no_undo;
DROP TRIGGER lifecycle_delivery_response_delete;
DROP TRIGGER lifecycle_delivery_response_update;
DROP TRIGGER lifecycle_delivery_response_insert;
DROP TRIGGER lifecycle_delivery_problem_delete;
DROP TRIGGER lifecycle_delivery_problem_update;
DROP TRIGGER lifecycle_delivery_problem_insert;
DROP TRIGGER lifecycle_receipt_delete;
DROP TRIGGER lifecycle_receipt_update;
DROP TRIGGER lifecycle_receipt_owner;
DROP TABLE lifecycle_delivery_responses;
DROP TABLE lifecycle_delivery_problems;
DROP TABLE lifecycle_receipts;
